# Site settings
title: 52IRL
email: info@doubtlessprayer.com
description: >know the difference between fiction and reality. # this means to ignore newlines until "baseurl:"
baseurl: "/home/" # the subpath of your site, e.g. /blog/
url: "site" # the base hostname & protocol for your site

twitter_username: @watchmanshi
github_username:

# Build settings
markdown: kramdown
